* checked added/deleted files in the snapshot

diff --git a/snapshot b/snapshot
--- a/snapshot
+++ b/snapshot
@@ -2,23 +2,42 @@
 
 #set -x
 
-elsarep=ithif59.inf.tu-dresden.de:/sun/theorie/tews/Privat/Store
+#elsarep=ithif59.inf.tu-dresden.de:/sun/theorie/tews/Privat/Store
+elsarep=/home/tews/Store
 repdir=src/elsa
+create_tar_cache=0
 
 dir=/tmp/tews/elsa
 cvscache=elsa.tar.gz
 
+orig_elsa_release_tar=/home/tews/src/elsa-2005.08.22b.tar.gz
 orig_elsa_release=/tmp/tews/elsa-2005.08.22b
 
 rm -rf $dir
 
+elsa_cvs_dir=$(pwd)
+
+echo ===========================================================================
+echo ============================     make doc    ==============================
+echo ===========================================================================
+
+#make doc
+
+echo ===========================================================================
+echo ============================     export    ================================
+echo ===========================================================================
+
+
 pushd $(dirname $dir)
 
-if [ -f $cvscache ] ; then
+
+if [ $create_tar_cache = 1 -a -f $cvscache ] ; then
     tar -xzf $cvscache
 else
     cvs -d $elsarep export -d $(basename $dir) -r HEAD $repdir
-    tar -czf $cvscache $(basename $dir)
+    if [ $create_tar_cache = 1 ] ; then
+	tar -czf $cvscache $(basename $dir)
+    fi
 fi
 
 cd $dir
@@ -29,64 +48,79 @@ done
 
 make distclean
 
+# cp gendoc dirs
+for d in smbase ast elkhound elsa ; do
+    cp -a $elsa_cvs_dir/$d/gendoc $d
+done
+
 
 echo ===========================================================================
 echo ============================     ADDED FILES    ===========================
 echo ===========================================================================
 
-add		elsa/ChangeLog
-generated 	/tmp/tews/elsa-2005.08.22b/ast/agrampar.codes.h
-generated 	/tmp/tews/elsa-2005.08.22b/ast/agrampar.tab.cc
-generated 	/tmp/tews/elsa-2005.08.22b/ast/agrampar.tab.h
-add		elsa/ast/ast_util.ml
-compile errors	/tmp/tews/elsa-2005.08.22b/ast/exampletest.cc
-
-fix gendoc problem:
-add gendoc subdirs to cvs ...
-
-/tmp/tews/elsa-2005.08.22b/ast/gendoc
-elsa/ast/ocamlhelp.cc
-elsa/ast/ocamlhelp.h
-elsa/ast/ocsstr.cc
-elsa/ast/ocsstr.h
-/tmp/tews/elsa-2005.08.22b/elkhound/c/lexer1yy.cc
-/tmp/tews/elsa-2005.08.22b/elkhound/examples/arith/arithyy.cc
-/tmp/tews/elsa-2005.08.22b/elkhound/gendoc
-/tmp/tews/elsa-2005.08.22b/elkhound/grampar.codes.h
-/tmp/tews/elsa-2005.08.22b/elkhound/grampar.tab.cc
-/tmp/tews/elsa-2005.08.22b/elkhound/grampar.tab.h
-elsa/elsa/all.ast
-elsa/elsa/ast_annotation.ml
-elsa/elsa/ast_marshal.ml
-elsa/elsa/caml_callbacks.ml
-elsa/elsa/cc_ml_constructors.ml
-elsa/elsa/cc_ml_types.ml
-elsa/elsa/cc_ocaml.cc
-elsa/elsa/cc_ocaml.h
-/tmp/tews/elsa-2005.08.22b/elsa/doc/er.ps
-elsa/elsa/doc/tracing-options.txt
-elsa/elsa/elsa_util.ml
-/tmp/tews/elsa-2005.08.22b/elsa/gendoc
-elsa/elsa/gnu_attribute_hack.ast
-elsa/elsa/in/c/.cvsignore
-elsa/elsa/in/c99/.cvsignore
-elsa/elsa/in/gnu/bugs/.cvsignore
-elsa/elsa/in/gnu/cil/.cvsignore
-elsa/elsa/in/kandr/.cvsignore
-elsa/elsa/in/msvc/.cvsignore
-elsa/elsa/in/std/.cvsignore
-elsa/elsa/ml_ctype.ast
-elsa/elsa/ml_ctype.ml
-elsa/elsa/ml_ctype_constructors.ml
-elsa/elsa/mldeps.mk
-elsa/semantic
-/tmp/tews/elsa-2005.08.22b/smbase/gendoc
-elsa/snapshot
+# added elsa/ChangeLog
+# added elsa/ast/ast_util.ml
+# added elsa/ast/ocamlhelp.cc
+# added elsa/ast/ocamlhelp.h
+# added elsa/ast/ocsstr.cc
+# added elsa/ast/ocsstr.h
+# added elsa/ChangeLog
+# added elsa/elsa/all.ast
+# added elsa/elsa/ast_annotation.ml
+# added elsa/elsa/ast_marshal.ml
+# added elsa/elsa/caml_callbacks.ml
+# added elsa/elsa/cc_ml_constructors.ml
+# added elsa/elsa/cc_ml_types.ml
+# added elsa/elsa/cc_ocaml.cc
+# added elsa/elsa/cc_ocaml.h
+# added elsa/elsa/doc/tracing-options.txt
+# added elsa/elsa/elsa_util.ml
+# added elsa/elsa/gnu_attribute_hack.ast
+# added elsa/elsa/in/c/.cvsignore
+# added elsa/elsa/in/c99/.cvsignore
+# added elsa/elsa/in/gnu/bugs/.cvsignore
+# added elsa/elsa/in/gnu/cil/.cvsignore
+# added elsa/elsa/in/kandr/.cvsignore
+# added elsa/elsa/in/msvc/.cvsignore
+# added elsa/elsa/in/std/.cvsignore
+# added elsa/elsa/ml_ctype.ast
+# added elsa/elsa/ml_ctype_constructors.ml
+# added elsa/elsa/ml_ctype.ml
+# added elsa/elsa/mldeps.mk
+# added elsa/semantic
+# added elsa/snapshot
+#
+# generated /tmp/tews/elsa-2005.08.22b/ast/agrampar.codes.h
+# generated /tmp/tews/elsa-2005.08.22b/ast/agrampar.tab.cc
+# generated /tmp/tews/elsa-2005.08.22b/ast/agrampar.tab.h
+# generated /tmp/tews/elsa-2005.08.22b/elkhound/c/lexer1yy.cc
+# generated /tmp/tews/elsa-2005.08.22b/elkhound/examples/arith/arithyy.cc
+# generated /tmp/tews/elsa-2005.08.22b/elkhound/grampar.codes.h
+# generated /tmp/tews/elsa-2005.08.22b/elkhound/grampar.tab.cc
+# generated /tmp/tews/elsa-2005.08.22b/elkhound/grampar.tab.h
+# compile errors	/tmp/tews/elsa-2005.08.22b/ast/exampletest.cc
+# ?? /tmp/tews/elsa-2005.08.22b/elsa/gendoc/.xvpics
+#       the file in there is also in elsa/doc
 
 
+if [ ! -d $orig_elsa_release ] ; then
+    if [ ! -f $orig_elsa_release_tar ] ; then
+	echo "need location of elsa-2005.08.22b.tar.gz"
+	exit 1
+    fi
+    
+    pushd $(dirname $dir)
+    tar -xzf $orig_elsa_release_tar
+    if [ ! -d $orig_elsa_release ] ; then
+	echo "something is wrong: untared original elsa but can't find it"
+	exit 1
+    fi
+    popd
+fi
 
 cd $(dirname $dir)
 diff -rq $(basename $dir) $orig_elsa_release | \
-    grep -v "differ$" | \
-    sed -e 's/Only in //' -e 's|: |/|'
+    grep -v -e 'differ$' | \
+    sed -e 's/Only in //' -e 's|: |/|' | \
+    grep -v -f $elsa_cvs_dir/addcheck_ignored_files
 
