fix t0335.cc: deleting an incomplete type

diff --git a/elsa/test-for-error b/elsa/test-for-error
--- a/elsa/test-for-error
+++ b/elsa/test-for-error
@@ -9,6 +9,7 @@ usage() {
   echo "    - goes through gcc, and"
   echo "    - provokes an error from ccparse, where"
   echo "    - the error message matches the fragment regexp"
+  echo "  Use the special msg \"segfault\" to test for a segfault."
 }
 
 # verbose operation?
@@ -56,10 +57,21 @@ else
 fi
 
 # ccparse
-if ./ccparse tmp.i 2>&1 | grep "$msg"; then
-  echo "found the error message I am looking for"
-  exit 0
+if [ "$msg" = "segfault" ]; then
+  ./ccparse tmp.i >/dev/null 2>&1
+  if [ "$?" = "139" ]; then
+    echo "got the segfault I am looking for"
+    exit 0
+  else
+    echo "did not get a segfault"
+    exit 4
+  fi
 else
-  echo "didn't get the error I want"
-  exit 4
+  if ./ccparse tmp.i 2>&1 | grep "$msg"; then
+    echo "found the error message I am looking for"
+    exit 0
+  else
+    echo "didn't get the error I want"
+    exit 4
+  fi
 fi
