simplified Makefile

diff --git a/elkhound/perimeter/testit b/elkhound/perimeter/testit
--- a/elkhound/perimeter/testit
+++ b/elkhound/perimeter/testit
@@ -1,25 +1,25 @@
 #!/bin/sh
 # test a perimeter binary
 
-if [ "$1" = "" ]; then
-  echo "usage: $0 ./perimeter.exe"
-  exit
+binary="./perimeter"
+if [ "$1" != "" ]; then
+  binary="$1"
 fi
 
 # all of perimeter's output is to stdout
-echo "running: $1 >output"
-if ! $1 >output; then
-  echo "$1 failed directly"
+echo "running: $binary >output"
+if ! $binary >output; then
+  echo "$binary failed directly"
   exit 2
 fi
 
 if ! grep -v "Time elapsed" <output | diff out.orig - >out.diff 2>&1  ; then
   # For some reason diff returns error code but an empty diff !
-  if test -s out.diff; then 
-     echo "$1 got the wrong answer. See out.diff."
+  if test -s out.diff; then
+     echo "$binary got the wrong answer. See out.diff."
      exit 4
   fi
 fi
-echo "$1 seems to work"
+echo "$binary seems to work"
 rm -f out.diff
  
